using MartinGC94.DisplayConfig.Native.Enums;

namespace MartinGC94.DisplayConfig.API
{
    public enum ColorMode : uint
    {
        SDR = DISPLAYCONFIG_ADVANCED_COLOR_MODE.DISPLAYCONFIG_ADVANCED_COLOR_MODE_SDR,
        WCG = DISPLAYCONFIG_ADVANCED_COLOR_MODE.DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG,
        HDR = DISPLAYCONFIG_ADVANCED_COLOR_MODE.DISPLAYCONFIG_ADVANCED_COLOR_MODE_HDR
    }
}